#ifndef BACKGROUND_EDITOR_H
# define BACKGROUND_EDITOR_H

# include <editor.h>
# include <doom_nukem.h>

# define ARROW_LEFT 0
# define ARROW_RIGHT 1

# define SQUARE_ACTION_SIDE_X 80
# define SQUARE_ACTION_SIDE_Y 50

# define SQUARE_SELECT_SX 1170
# define SQUARE_SELECT_SY 224
# define SQUARE_SELECT_EX SQUARE_SELECT_SX + SQUARE_ACTION_SIDE_X
# define SQUARE_SELECT_EY SQUARE_SELECT_SY + SQUARE_ACTION_SIDE_Y

# define SQUARE_MOVE_SX 1291
# define SQUARE_MOVE_SY 224
# define SQUARE_MOVE_EX SQUARE_MOVE_SX + SQUARE_ACTION_SIDE_X
# define SQUARE_MOVE_EY SQUARE_MOVE_SY + SQUARE_ACTION_SIDE_Y

# define SQUARE_DELETE_SX 1412
# define SQUARE_DELETE_SY 224
# define SQUARE_DELETE_EX SQUARE_DELETE_SX + SQUARE_ACTION_SIDE_X
# define SQUARE_DELETE_EY SQUARE_DELETE_SY + SQUARE_ACTION_SIDE_Y

# define SQUARE_SAVE_SX 1197
# define SQUARE_SAVE_SY 960
# define SQUARE_SAVE_EX 1494
# define SQUARE_SAVE_EY 1002

# define SQUARE_DRAW_SX 1148
# define SQUARE_DRAW_SY 335
# define SQUARE_DRAW_EX SQUARE_DRAW_SX + SQUARE_ACTION_SIDE_X
# define SQUARE_DRAW_EY SQUARE_DRAW_SY + SQUARE_ACTION_SIDE_Y

#define WALL_TYPE_RED_SX 1275
#define WALL_TYPE_RED_SY 349
#define WALL_TYPE_RED_EX WALL_TYPE_RED_SX + WALL_TYPE_SIDE
#define WALL_TYPE_RED_EY WALL_TYPE_RED_SY + WALL_TYPE_SIDE

#define WALL_TYPE_WHITE_SX 1409
#define WALL_TYPE_WHITE_SY 349
#define WALL_TYPE_WHITE_EX WALL_TYPE_WHITE_SX + WALL_TYPE_SIDE
#define WALL_TYPE_WHITE_EY WALL_TYPE_WHITE_SY + WALL_TYPE_SIDE

# define ARROW_GAP 101
# define ARROW_START 15
# define ARROW_SIZE_X 17
# define ARROW_SIZE_Y 23
# define TEXTURE_POS_X 31
# define TEXTURE_POS_Y -26
/*# define ARROW_SIDE 17*/

# define SECTOR_NUM_X 1274
# define SECTOR_NUM_Y 590

# define UP_LEFT_ARROW_X 1122
# define UP_LEFT_ARROW_Y 436
# define UP_LEFT_ARROW_SX UP_LEFT_ARROW_X
# define UP_LEFT_ARROW_SY UP_LEFT_ARROW_Y + ARROW_START
# define UP_LEFT_ARROW_EX UP_LEFT_ARROW_X + ARROW_SIZE_X
# define UP_LEFT_ARROW_EY UP_LEFT_ARROW_SY + ARROW_SIZE_Y
/*# define UP_RIGHT_ARROW_X UP_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)*/
/*# define UP_RIGHT_ARROW_Y UP_LEFT_ARROW_Y*/
# define UP_RIGHT_ARROW_SX UP_LEFT_ARROW_SX + ARROW_GAP
# define UP_RIGHT_ARROW_SY UP_LEFT_ARROW_SY
# define UP_RIGHT_ARROW_EX UP_RIGHT_ARROW_SX + ARROW_SIZE_X
# define UP_RIGHT_ARROW_EY UP_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define UP_TEXTURE_X UP_LEFT_ARROW_X + TEXTURE_POS_X
# define UP_TEXTURE_Y UP_LEFT_ARROW_Y

# define DOWN_LEFT_ARROW_X 1272
# define DOWN_LEFT_ARROW_Y 436
# define DOWN_LEFT_ARROW_SX DOWN_LEFT_ARROW_X
# define DOWN_LEFT_ARROW_SY DOWN_LEFT_ARROW_Y + ARROW_START
# define DOWN_LEFT_ARROW_EX DOWN_LEFT_ARROW_X + ARROW_SIZE_X
# define DOWN_LEFT_ARROW_EY DOWN_LEFT_ARROW_SY + ARROW_SIZE_Y
/*# define DOWN_RIGHT_ARROW_X DOWN_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)
# define DOWN_RIGHT_ARROW_Y DOWN_LEFT_ARROW_Y*/
# define DOWN_RIGHT_ARROW_SX DOWN_LEFT_ARROW_SX + ARROW_GAP
# define DOWN_RIGHT_ARROW_SY DOWN_LEFT_ARROW_SY
# define DOWN_RIGHT_ARROW_EX DOWN_RIGHT_ARROW_SX + ARROW_SIZE_X
# define DOWN_RIGHT_ARROW_EY DOWN_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define DOWN_TEXTURE_X DOWN_LEFT_ARROW_X + TEXTURE_POS_X
# define DOWN_TEXTURE_Y DOWN_LEFT_ARROW_Y


# define WALL_LEFT_ARROW_X 1422
# define WALL_LEFT_ARROW_Y 436
# define WALL_LEFT_ARROW_SX WALL_LEFT_ARROW_X
# define WALL_LEFT_ARROW_SY WALL_LEFT_ARROW_Y + ARROW_START
# define WALL_LEFT_ARROW_EX WALL_LEFT_ARROW_X + ARROW_SIZE_X
# define WALL_LEFT_ARROW_EY WALL_LEFT_ARROW_SY + ARROW_SIZE_Y
# define WALL_RIGHT_ARROW_SX WALL_LEFT_ARROW_SX + ARROW_GAP
# define WALL_RIGHT_ARROW_SY WALL_LEFT_ARROW_SY 
# define WALL_RIGHT_ARROW_EX WALL_RIGHT_ARROW_SX + ARROW_SIZE_X
# define WALL_RIGHT_ARROW_EY WALL_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define WALL_TEXTURE_X WALL_LEFT_ARROW_X + TEXTURE_POS_X
# define WALL_TEXTURE_Y WALL_LEFT_ARROW_Y


# define LIGHT_LEFT_ARROW_X 1413
# define LIGHT_LEFT_ARROW_Y 576
# define LIGHT_LEFT_ARROW_SX LIGHT_LEFT_ARROW_X
# define LIGHT_LEFT_ARROW_SY LIGHT_LEFT_ARROW_Y + ARROW_START
# define LIGHT_LEFT_ARROW_EX LIGHT_LEFT_ARROW_X + ARROW_SIZE_X
# define LIGHT_LEFT_ARROW_EY LIGHT_LEFT_ARROW_SY + ARROW_SIZE_Y
# define LIGHT_RIGHT_ARROW_SX LIGHT_LEFT_ARROW_SX + ARROW_GAP
# define LIGHT_RIGHT_ARROW_SY LIGHT_LEFT_ARROW_SY
# define LIGHT_RIGHT_ARROW_EX LIGHT_RIGHT_ARROW_SX + ARROW_SIZE_X
# define LIGHT_RIGHT_ARROW_EY LIGHT_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define LIGHT_VALUE_X LIGHT_LEFT_ARROW_X + TEXTURE_POS_X + 9
# define LIGHT_VALUE_Y LIGHT_LEFT_ARROW_Y + 16

# define CEIL_TEXT_LEFT_ARROW_X 1413
# define CEIL_TEXT_LEFT_ARROW_Y 672
# define CEIL_TEXT_LEFT_ARROW_SX CEIL_TEXT_LEFT_ARROW_X
# define CEIL_TEXT_LEFT_ARROW_SY CEIL_TEXT_LEFT_ARROW_Y + ARROW_START
# define CEIL_TEXT_LEFT_ARROW_EX CEIL_TEXT_LEFT_ARROW_X + ARROW_SIZE_X
# define CEIL_TEXT_LEFT_ARROW_EY CEIL_TEXT_LEFT_ARROW_SY + ARROW_SIZE_Y
# define CEIL_TEXT_RIGHT_ARROW_SX CEIL_TEXT_LEFT_ARROW_SX + ARROW_GAP
# define CEIL_TEXT_RIGHT_ARROW_SY CEIL_TEXT_LEFT_ARROW_SY
# define CEIL_TEXT_RIGHT_ARROW_EX CEIL_TEXT_RIGHT_ARROW_SX + ARROW_SIZE_X
# define CEIL_TEXT_RIGHT_ARROW_EY CEIL_TEXT_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define CEIL_TEXT_TEXTURE_X CEIL_TEXT_LEFT_ARROW_X + TEXTURE_POS_X
# define CEIL_TEXT_TEXTURE_Y CEIL_TEXT_LEFT_ARROW_Y

# define FLOOR_TEXT_LEFT_ARROW_X 1413
# define FLOOR_TEXT_LEFT_ARROW_Y 802
# define FLOOR_TEXT_LEFT_ARROW_SX FLOOR_TEXT_LEFT_ARROW_X
# define FLOOR_TEXT_LEFT_ARROW_SY FLOOR_TEXT_LEFT_ARROW_Y + ARROW_START
# define FLOOR_TEXT_LEFT_ARROW_EX FLOOR_TEXT_LEFT_ARROW_X + ARROW_SIZE_X
# define FLOOR_TEXT_LEFT_ARROW_EY FLOOR_TEXT_LEFT_ARROW_SY + ARROW_SIZE_Y
# define FLOOR_TEXT_RIGHT_ARROW_SX FLOOR_TEXT_LEFT_ARROW_SX + ARROW_GAP
# define FLOOR_TEXT_RIGHT_ARROW_SY FLOOR_TEXT_LEFT_ARROW_SY
# define FLOOR_TEXT_RIGHT_ARROW_EX FLOOR_TEXT_RIGHT_ARROW_SX + ARROW_SIZE_X
# define FLOOR_TEXT_RIGHT_ARROW_EY FLOOR_TEXT_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define FLOOR_TEXT_TEXTURE_X FLOOR_TEXT_LEFT_ARROW_X + TEXTURE_POS_X
# define FLOOR_TEXT_TEXTURE_Y FLOOR_TEXT_LEFT_ARROW_Y

// HEIGHT

# define CEIL_HEIGHT_LEFT_ARROW_X 1277
# define CEIL_HEIGHT_LEFT_ARROW_Y 672
# define CEIL_HEIGHT_LEFT_ARROW_SX CEIL_HEIGHT_LEFT_ARROW_X
# define CEIL_HEIGHT_LEFT_ARROW_SY CEIL_HEIGHT_LEFT_ARROW_Y + ARROW_START
# define CEIL_HEIGHT_LEFT_ARROW_EX CEIL_HEIGHT_LEFT_ARROW_X + ARROW_SIZE_X
# define CEIL_HEIGHT_LEFT_ARROW_EY CEIL_HEIGHT_LEFT_ARROW_SY + ARROW_SIZE_Y
# define CEIL_HEIGHT_RIGHT_ARROW_SX CEIL_HEIGHT_LEFT_ARROW_SX + ARROW_GAP
# define CEIL_HEIGHT_RIGHT_ARROW_SY CEIL_HEIGHT_LEFT_ARROW_SY
# define CEIL_HEIGHT_RIGHT_ARROW_EX CEIL_HEIGHT_RIGHT_ARROW_SX + ARROW_SIZE_X
# define CEIL_HEIGHT_RIGHT_ARROW_EY CEIL_HEIGHT_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define CEIL_HEIGHT_VALUE_X CEIL_HEIGHT_LEFT_ARROW_X + TEXTURE_POS_X + 11
# define CEIL_HEIGHT_VALUE_Y CEIL_HEIGHT_LEFT_ARROW_Y + 16

# define FLOOR_HEIGHT_LEFT_ARROW_X 1273
# define FLOOR_HEIGHT_LEFT_ARROW_Y 802
# define FLOOR_HEIGHT_LEFT_ARROW_SX FLOOR_HEIGHT_LEFT_ARROW_X
# define FLOOR_HEIGHT_LEFT_ARROW_SY FLOOR_HEIGHT_LEFT_ARROW_Y + ARROW_START
# define FLOOR_HEIGHT_LEFT_ARROW_EX FLOOR_HEIGHT_LEFT_ARROW_X + ARROW_SIZE_X
# define FLOOR_HEIGHT_LEFT_ARROW_EY FLOOR_HEIGHT_LEFT_ARROW_SY + ARROW_SIZE_Y
# define FLOOR_HEIGHT_RIGHT_ARROW_SX FLOOR_HEIGHT_LEFT_ARROW_SX + ARROW_GAP
# define FLOOR_HEIGHT_RIGHT_ARROW_SY FLOOR_HEIGHT_LEFT_ARROW_SY
# define FLOOR_HEIGHT_RIGHT_ARROW_EX FLOOR_HEIGHT_RIGHT_ARROW_SX + ARROW_SIZE_X
# define FLOOR_HEIGHT_RIGHT_ARROW_EY FLOOR_HEIGHT_RIGHT_ARROW_SY + ARROW_SIZE_Y
# define FLOOR_HEIGHT_VALUE_X FLOOR_HEIGHT_LEFT_ARROW_X + TEXTURE_POS_X + 12
# define FLOOR_HEIGHT_VALUE_Y FLOOR_HEIGHT_LEFT_ARROW_Y + 16

# define SMALL_ARROW_GAP 30
# define SMALL_ARROW_SIDE 12
# define SMALL_ARROW_TO_ARROW 76

# define SMALL_X_CEIL_LEFT_ARROW_X 1157
# define SMALL_X_CEIL_LEFT_ARROW_Y 687
# define SMALL_X_CEIL_LEFT_ARROW_SX SMALL_X_CEIL_LEFT_ARROW_X
# define SMALL_X_CEIL_LEFT_ARROW_SY SMALL_X_CEIL_LEFT_ARROW_Y
# define SMALL_X_CEIL_LEFT_ARROW_EX SMALL_X_CEIL_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_X_CEIL_LEFT_ARROW_EY SMALL_X_CEIL_LEFT_ARROW_Y + SMALL_ARROW_SIDE
# define SMALL_X_CEIL_RIGHT_ARROW_SX SMALL_X_CEIL_LEFT_ARROW_X + SMALL_ARROW_TO_ARROW
# define SMALL_X_CEIL_RIGHT_ARROW_SY SMALL_X_CEIL_LEFT_ARROW_Y
# define SMALL_X_CEIL_RIGHT_ARROW_EX SMALL_X_CEIL_RIGHT_ARROW_SX + SMALL_ARROW_SIDE
# define SMALL_X_CEIL_RIGHT_ARROW_EY SMALL_X_CEIL_RIGHT_ARROW_SY + SMALL_ARROW_SIDE
# define SMALL_X_CEIL_VALUE_X SMALL_X_CEIL_LEFT_ARROW_X + SMALL_ARROW_GAP
# define SMALL_X_CEIL_VALUE_Y SMALL_X_CEIL_LEFT_ARROW_Y - 10

# define SMALL_Y_CEIL_LEFT_ARROW_X 1157
# define SMALL_Y_CEIL_LEFT_ARROW_Y 709
# define SMALL_Y_CEIL_LEFT_ARROW_SX SMALL_Y_CEIL_LEFT_ARROW_X
# define SMALL_Y_CEIL_LEFT_ARROW_SY SMALL_Y_CEIL_LEFT_ARROW_Y
# define SMALL_Y_CEIL_LEFT_ARROW_EX SMALL_Y_CEIL_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_Y_CEIL_LEFT_ARROW_EY SMALL_Y_CEIL_LEFT_ARROW_Y + SMALL_ARROW_SIDE
# define SMALL_Y_CEIL_RIGHT_ARROW_SX SMALL_Y_CEIL_LEFT_ARROW_X + SMALL_ARROW_TO_ARROW
# define SMALL_Y_CEIL_RIGHT_ARROW_SY SMALL_Y_CEIL_LEFT_ARROW_Y
# define SMALL_Y_CEIL_RIGHT_ARROW_EX SMALL_Y_CEIL_RIGHT_ARROW_SX + SMALL_ARROW_SIDE
# define SMALL_Y_CEIL_RIGHT_ARROW_EY SMALL_Y_CEIL_RIGHT_ARROW_SY + SMALL_ARROW_SIDE
# define SMALL_Y_CEIL_VALUE_X SMALL_Y_CEIL_LEFT_ARROW_X + SMALL_ARROW_GAP
# define SMALL_Y_CEIL_VALUE_Y SMALL_Y_CEIL_LEFT_ARROW_Y - 10

# define SMALL_X_FLOOR_LEFT_ARROW_X 1157
# define SMALL_X_FLOOR_LEFT_ARROW_Y 822
# define SMALL_X_FLOOR_LEFT_ARROW_SX SMALL_X_FLOOR_LEFT_ARROW_X
# define SMALL_X_FLOOR_LEFT_ARROW_SY SMALL_X_FLOOR_LEFT_ARROW_Y
# define SMALL_X_FLOOR_LEFT_ARROW_EX SMALL_X_FLOOR_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_X_FLOOR_LEFT_ARROW_EY SMALL_X_FLOOR_LEFT_ARROW_Y + SMALL_ARROW_SIDE
# define SMALL_X_FLOOR_RIGHT_ARROW_SX SMALL_X_FLOOR_LEFT_ARROW_X + SMALL_ARROW_TO_ARROW
# define SMALL_X_FLOOR_RIGHT_ARROW_SY SMALL_X_FLOOR_LEFT_ARROW_Y
# define SMALL_X_FLOOR_RIGHT_ARROW_EX SMALL_X_FLOOR_RIGHT_ARROW_SX + SMALL_ARROW_SIDE
# define SMALL_X_FLOOR_RIGHT_ARROW_EY SMALL_X_FLOOR_RIGHT_ARROW_SY + SMALL_ARROW_SIDE
# define SMALL_X_FLOOR_VALUE_X SMALL_X_FLOOR_LEFT_ARROW_X + SMALL_ARROW_GAP
# define SMALL_X_FLOOR_VALUE_Y SMALL_X_FLOOR_LEFT_ARROW_Y - 10

# define SMALL_Y_FLOOR_LEFT_ARROW_X 1157
# define SMALL_Y_FLOOR_LEFT_ARROW_Y 842
# define SMALL_Y_FLOOR_LEFT_ARROW_SX SMALL_Y_FLOOR_LEFT_ARROW_X
# define SMALL_Y_FLOOR_LEFT_ARROW_SY SMALL_Y_FLOOR_LEFT_ARROW_Y
# define SMALL_Y_FLOOR_LEFT_ARROW_EX SMALL_Y_FLOOR_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_Y_FLOOR_LEFT_ARROW_EY SMALL_Y_FLOOR_LEFT_ARROW_Y + SMALL_ARROW_SIDE
# define SMALL_Y_FLOOR_RIGHT_ARROW_SX SMALL_Y_FLOOR_LEFT_ARROW_X + SMALL_ARROW_TO_ARROW
# define SMALL_Y_FLOOR_RIGHT_ARROW_SY SMALL_Y_FLOOR_LEFT_ARROW_Y
# define SMALL_Y_FLOOR_RIGHT_ARROW_EX SMALL_Y_FLOOR_RIGHT_ARROW_SX + SMALL_ARROW_SIDE
# define SMALL_Y_FLOOR_RIGHT_ARROW_EY SMALL_Y_FLOOR_RIGHT_ARROW_SY + SMALL_ARROW_SIDE
# define SMALL_Y_FLOOR_VALUE_X SMALL_Y_FLOOR_LEFT_ARROW_X + SMALL_ARROW_GAP
# define SMALL_Y_FLOOR_VALUE_Y SMALL_Y_FLOOR_LEFT_ARROW_Y - 10

#define WALL_TYPE_SIDE 30

// END


/*# define SQUARE_ACTION_SIDE 70

# define SQUARE_SELECT_SX 1128
# define SQUARE_SELECT_SY 222
# define SQUARE_SELECT_EX SQUARE_SELECT_SX + SQUARE_ACTION_SIDE
# define SQUARE_SELECT_EY SQUARE_SELECT_SY + SQUARE_ACTION_SIDE

# define SQUARE_MOVE_SX 1239
# define SQUARE_MOVE_SY 222
# define SQUARE_MOVE_EX SQUARE_MOVE_SX + SQUARE_ACTION_SIDE
# define SQUARE_MOVE_EY SQUARE_MOVE_SY + SQUARE_ACTION_SIDE

# define SQUARE_DELETE_SX 1352
# define SQUARE_DELETE_SY 222
# define SQUARE_DELETE_EX SQUARE_DELETE_SX + SQUARE_ACTION_SIDE
# define SQUARE_DELETE_EY SQUARE_DELETE_SY + SQUARE_ACTION_SIDE

# define SQUARE_SAVE_SX 1466
# define SQUARE_SAVE_SY 222
# define SQUARE_SAVE_EX SQUARE_SAVE_SX + SQUARE_ACTION_SIDE
# define SQUARE_SAVE_EY SQUARE_SAVE_SY + SQUARE_ACTION_SIDE

# define SQUARE_DRAW_SX 1148
# define SQUARE_DRAW_SY 372
# define SQUARE_DRAW_EX SQUARE_DRAW_SX + SQUARE_ACTION_SIDE
# define SQUARE_DRAW_EY SQUARE_DRAW_SY + SQUARE_ACTION_SIDE

# define ARROW_GAP 105
# define ARROW_SIDE 16
# define TEXTURE_POS_X 26
# define TEXTURE_POS_Y -26

# define SECTOR_NUM_X 1296
# define SECTOR_NUM_Y 695

# define UP_LEFT_ARROW_X 1128
# define UP_LEFT_ARROW_Y 526
# define UP_LEFT_ARROW_SX UP_LEFT_ARROW_X
# define UP_LEFT_ARROW_SY UP_LEFT_ARROW_Y - ARROW_SIDE / 2
# define UP_LEFT_ARROW_EX UP_LEFT_ARROW_X + ARROW_SIDE
# define UP_LEFT_ARROW_EY UP_LEFT_ARROW_Y + ARROW_SIDE / 2
# define UP_RIGHT_ARROW_X UP_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)
# define UP_RIGHT_ARROW_Y UP_LEFT_ARROW_Y
# define UP_RIGHT_ARROW_SX UP_RIGHT_ARROW_X
# define UP_RIGHT_ARROW_SY UP_RIGHT_ARROW_Y - ARROW_SIDE / 2
# define UP_RIGHT_ARROW_EX UP_RIGHT_ARROW_X + ARROW_SIDE
# define UP_RIGHT_ARROW_EY UP_RIGHT_ARROW_Y + ARROW_SIDE / 2
# define UP_TEXTURE_X UP_LEFT_ARROW_X + TEXTURE_POS_X
# define UP_TEXTURE_Y UP_LEFT_ARROW_Y + TEXTURE_POS_Y

# define DOWN_LEFT_ARROW_X 1277
# define DOWN_LEFT_ARROW_Y 526
# define DOWN_LEFT_ARROW_SX DOWN_LEFT_ARROW_X
# define DOWN_LEFT_ARROW_SY DOWN_LEFT_ARROW_Y - ARROW_SIDE / 2
# define DOWN_LEFT_ARROW_EX DOWN_LEFT_ARROW_X + ARROW_SIDE
# define DOWN_LEFT_ARROW_EY DOWN_LEFT_ARROW_Y + ARROW_SIDE / 2
# define DOWN_RIGHT_ARROW_X DOWN_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)
# define DOWN_RIGHT_ARROW_Y DOWN_LEFT_ARROW_Y
# define DOWN_RIGHT_ARROW_SX DOWN_RIGHT_ARROW_X
# define DOWN_RIGHT_ARROW_SY DOWN_RIGHT_ARROW_Y - ARROW_SIDE / 2
# define DOWN_RIGHT_ARROW_EX DOWN_RIGHT_ARROW_X + ARROW_SIDE
# define DOWN_RIGHT_ARROW_EY DOWN_RIGHT_ARROW_Y + ARROW_SIDE / 2
# define DOWN_TEXTURE_X DOWN_LEFT_ARROW_X + TEXTURE_POS_X
# define DOWN_TEXTURE_Y DOWN_LEFT_ARROW_Y + TEXTURE_POS_Y

# define WALL_LEFT_ARROW_X 1426
# define WALL_LEFT_ARROW_Y 526
# define WALL_LEFT_ARROW_SX WALL_LEFT_ARROW_X
# define WALL_LEFT_ARROW_SY WALL_LEFT_ARROW_Y - ARROW_SIDE / 2
# define WALL_LEFT_ARROW_EX WALL_LEFT_ARROW_X + ARROW_SIDE
# define WALL_LEFT_ARROW_EY WALL_LEFT_ARROW_Y + ARROW_SIDE / 2
# define WALL_RIGHT_ARROW_SX (WALL_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE))
# define WALL_RIGHT_ARROW_SY (WALL_LEFT_ARROW_Y) - ARROW_SIDE / 2
# define WALL_RIGHT_ARROW_EX (WALL_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)) + ARROW_SIDE
# define WALL_RIGHT_ARROW_EY (WALL_LEFT_ARROW_Y) + ARROW_SIDE / 2
# define WALL_TEXTURE_X WALL_LEFT_ARROW_X + TEXTURE_POS_X
# define WALL_TEXTURE_Y WALL_LEFT_ARROW_Y + TEXTURE_POS_Y

# define LIGHT_LEFT_ARROW_X 1426
# define LIGHT_LEFT_ARROW_Y 705
# define LIGHT_LEFT_ARROW_SX LIGHT_LEFT_ARROW_X
# define LIGHT_LEFT_ARROW_SY LIGHT_LEFT_ARROW_Y - ARROW_SIDE / 2
# define LIGHT_LEFT_ARROW_EX LIGHT_LEFT_ARROW_X + ARROW_SIDE
# define LIGHT_LEFT_ARROW_EY LIGHT_LEFT_ARROW_Y + ARROW_SIDE / 2
# define LIGHT_RIGHT_ARROW_SX (LIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE))
# define LIGHT_RIGHT_ARROW_SY (LIGHT_LEFT_ARROW_Y) - ARROW_SIDE / 2
# define LIGHT_RIGHT_ARROW_EX (LIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)) + ARROW_SIDE
# define LIGHT_RIGHT_ARROW_EY (LIGHT_LEFT_ARROW_Y) + ARROW_SIDE / 2
# define LIGHT_VALUE_X LIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE) / 2 - 3
# define LIGHT_VALUE_Y LIGHT_LEFT_ARROW_Y - 10
*/

/*# define CEIL_TEXT_LEFT_ARROW_X 1416
# define CEIL_TEXT_LEFT_ARROW_Y 829
# define CEIL_TEXT_LEFT_ARROW_SX CEIL_TEXT_LEFT_ARROW_X
# define CEIL_TEXT_LEFT_ARROW_SY CEIL_TEXT_LEFT_ARROW_Y - ARROW_SIDE / 2
# define CEIL_TEXT_LEFT_ARROW_EX CEIL_TEXT_LEFT_ARROW_X + ARROW_SIDE
# define CEIL_TEXT_LEFT_ARROW_EY CEIL_TEXT_LEFT_ARROW_Y + ARROW_SIDE / 2
# define CEIL_TEXT_RIGHT_ARROW_SX (CEIL_TEXT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE))
# define CEIL_TEXT_RIGHT_ARROW_SY (CEIL_TEXT_LEFT_ARROW_Y) - ARROW_SIDE / 2
# define CEIL_TEXT_RIGHT_ARROW_EX (CEIL_TEXT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)) + ARROW_SIDE
# define CEIL_TEXT_RIGHT_ARROW_EY (CEIL_TEXT_LEFT_ARROW_Y) + ARROW_SIDE / 2
# define CEIL_TEXT_TEXTURE_X CEIL_TEXT_LEFT_ARROW_X + TEXTURE_POS_X
# define CEIL_TEXT_TEXTURE_Y CEIL_TEXT_LEFT_ARROW_Y + TEXTURE_POS_Y
*/
/*# define CEIL_HEIGHT_LEFT_ARROW_X 1282
# define CEIL_HEIGHT_LEFT_ARROW_Y 829
# define CEIL_HEIGHT_LEFT_ARROW_SX CEIL_HEIGHT_LEFT_ARROW_X
# define CEIL_HEIGHT_LEFT_ARROW_SY CEIL_HEIGHT_LEFT_ARROW_Y - ARROW_SIDE / 2
# define CEIL_HEIGHT_LEFT_ARROW_EX CEIL_HEIGHT_LEFT_ARROW_X + ARROW_SIDE
# define CEIL_HEIGHT_LEFT_ARROW_EY CEIL_HEIGHT_LEFT_ARROW_Y + ARROW_SIDE / 2
# define CEIL_HEIGHT_RIGHT_ARROW_SX (CEIL_HEIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE))
# define CEIL_HEIGHT_RIGHT_ARROW_SY (CEIL_HEIGHT_LEFT_ARROW_Y) - ARROW_SIDE / 2
# define CEIL_HEIGHT_RIGHT_ARROW_EX (CEIL_HEIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)) + ARROW_SIDE
# define CEIL_HEIGHT_RIGHT_ARROW_EY (CEIL_HEIGHT_LEFT_ARROW_Y) + ARROW_SIDE / 2
# define CEIL_HEIGHT_VALUE_X CEIL_HEIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE) / 2 - 3
# define CEIL_HEIGHT_VALUE_Y CEIL_HEIGHT_LEFT_ARROW_Y - 10
*/
/*# define FLOOR_TEXT_LEFT_ARROW_X 1416
# define FLOOR_TEXT_LEFT_ARROW_Y 955
# define FLOOR_TEXT_LEFT_ARROW_SX FLOOR_TEXT_LEFT_ARROW_X
# define FLOOR_TEXT_LEFT_ARROW_SY FLOOR_TEXT_LEFT_ARROW_Y - ARROW_SIDE / 2
# define FLOOR_TEXT_LEFT_ARROW_EX FLOOR_TEXT_LEFT_ARROW_X + ARROW_SIDE
# define FLOOR_TEXT_LEFT_ARROW_EY FLOOR_TEXT_LEFT_ARROW_Y + ARROW_SIDE / 2
# define FLOOR_TEXT_RIGHT_ARROW_SX (FLOOR_TEXT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE))
# define FLOOR_TEXT_RIGHT_ARROW_SY (FLOOR_TEXT_LEFT_ARROW_Y) - ARROW_SIDE / 2
# define FLOOR_TEXT_RIGHT_ARROW_EX (FLOOR_TEXT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)) + ARROW_SIDE
# define FLOOR_TEXT_RIGHT_ARROW_EY (FLOOR_TEXT_LEFT_ARROW_Y) + ARROW_SIDE / 2
# define FLOOR_TEXT_TEXTURE_X FLOOR_TEXT_LEFT_ARROW_X + TEXTURE_POS_X
# define FLOOR_TEXT_TEXTURE_Y FLOOR_TEXT_LEFT_ARROW_Y + TEXTURE_POS_Y
*/
/*# define FLOOR_HEIGHT_LEFT_ARROW_X 1276
# define FLOOR_HEIGHT_LEFT_ARROW_Y 955
# define FLOOR_HEIGHT_LEFT_ARROW_SX FLOOR_HEIGHT_LEFT_ARROW_X
# define FLOOR_HEIGHT_LEFT_ARROW_SY FLOOR_HEIGHT_LEFT_ARROW_Y - ARROW_SIDE / 2
# define FLOOR_HEIGHT_LEFT_ARROW_EX FLOOR_HEIGHT_LEFT_ARROW_X + ARROW_SIDE
# define FLOOR_HEIGHT_LEFT_ARROW_EY FLOOR_HEIGHT_LEFT_ARROW_Y + ARROW_SIDE / 2
# define FLOOR_HEIGHT_RIGHT_ARROW_SX (FLOOR_HEIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE))
# define FLOOR_HEIGHT_RIGHT_ARROW_SY (FLOOR_HEIGHT_LEFT_ARROW_Y) - ARROW_SIDE / 2
# define FLOOR_HEIGHT_RIGHT_ARROW_EX (FLOOR_HEIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE)) + ARROW_SIDE
# define FLOOR_HEIGHT_RIGHT_ARROW_EY (FLOOR_HEIGHT_LEFT_ARROW_Y) + ARROW_SIDE / 2
# define FLOOR_HEIGHT_VALUE_X FLOOR_HEIGHT_LEFT_ARROW_X + (ARROW_GAP - ARROW_SIDE) / 2 - 3
# define FLOOR_HEIGHT_VALUE_Y FLOOR_HEIGHT_LEFT_ARROW_Y - 10
*/
/*# define SMALL_ARROW_GAP 82
# define SMALL_ARROW_SIDE 8

# define SMALL_X_CEIL_LEFT_ARROW_X 1159
# define SMALL_X_CEIL_LEFT_ARROW_Y 687
# define SMALL_X_CEIL_LEFT_ARROW_SX SMALL_X_CEIL_LEFT_ARROW_X
# define SMALL_X_CEIL_LEFT_ARROW_SY SMALL_X_CEIL_LEFT_ARROW_Y - SMALL_ARROW_SIDE / 2
# define SMALL_X_CEIL_LEFT_ARROW_EX SMALL_X_CEIL_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_X_CEIL_LEFT_ARROW_EY SMALL_X_CEIL_LEFT_ARROW_Y + SMALL_ARROW_SIDE / 2
# define SMALL_X_CEIL_RIGHT_ARROW_SX (SMALL_X_CEIL_LEFT_ARROW_X + SMALL_ARROW_GAP - SMALL_ARROW_SIDE)
# define SMALL_X_CEIL_RIGHT_ARROW_SY (SMALL_X_CEIL_LEFT_ARROW_Y) - SMALL_ARROW_SIDE / 2
# define SMALL_X_CEIL_RIGHT_ARROW_EX (SMALL_X_CEIL_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE)) + SMALL_ARROW_SIDE
# define SMALL_X_CEIL_RIGHT_ARROW_EY (SMALL_X_CEIL_LEFT_ARROW_Y) + SMALL_ARROW_SIDE / 2
# define SMALL_X_CEIL_VALUE_X SMALL_X_CEIL_LEFT_ARROW_X + SMALL_ARROW_GAP / 2 - 5
# define SMALL_X_CEIL_VALUE_Y SMALL_X_CEIL_LEFT_ARROW_Y - 10

# define SMALL_Y_CEIL_LEFT_ARROW_X 1159
# define SMALL_Y_CEIL_LEFT_ARROW_Y 709
# define SMALL_Y_CEIL_LEFT_ARROW_SX SMALL_Y_CEIL_LEFT_ARROW_X
# define SMALL_Y_CEIL_LEFT_ARROW_SY SMALL_Y_CEIL_LEFT_ARROW_Y - SMALL_ARROW_SIDE / 2
# define SMALL_Y_CEIL_LEFT_ARROW_EX SMALL_Y_CEIL_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_Y_CEIL_LEFT_ARROW_EY SMALL_Y_CEIL_LEFT_ARROW_Y + SMALL_ARROW_SIDE / 2
# define SMALL_Y_CEIL_RIGHT_ARROW_SX (SMALL_Y_CEIL_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE))
# define SMALL_Y_CEIL_RIGHT_ARROW_SY (SMALL_Y_CEIL_LEFT_ARROW_Y) - SMALL_ARROW_SIDE / 2
# define SMALL_Y_CEIL_RIGHT_ARROW_EX (SMALL_Y_CEIL_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE)) + SMALL_ARROW_SIDE
# define SMALL_Y_CEIL_RIGHT_ARROW_EY (SMALL_Y_CEIL_LEFT_ARROW_Y) + SMALL_ARROW_SIDE / 2
# define SMALL_Y_CEIL_VALUE_X SMALL_Y_CEIL_LEFT_ARROW_X + SMALL_ARROW_GAP / 2 - 5
# define SMALL_Y_CEIL_VALUE_Y SMALL_Y_CEIL_LEFT_ARROW_Y - 10

# define SMALL_X_FLOOR_LEFT_ARROW_X 1159
# define SMALL_X_FLOOR_LEFT_ARROW_Y 822
# define SMALL_X_FLOOR_LEFT_ARROW_SX SMALL_X_FLOOR_LEFT_ARROW_X
# define SMALL_X_FLOOR_LEFT_ARROW_SY SMALL_X_FLOOR_LEFT_ARROW_Y - SMALL_ARROW_SIDE / 2
# define SMALL_X_FLOOR_LEFT_ARROW_EX SMALL_X_FLOOR_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_X_FLOOR_LEFT_ARROW_EY SMALL_X_FLOOR_LEFT_ARROW_Y + SMALL_ARROW_SIDE / 2
# define SMALL_X_FLOOR_RIGHT_ARROW_SX (SMALL_X_FLOOR_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE))
# define SMALL_X_FLOOR_RIGHT_ARROW_SY (SMALL_X_FLOOR_LEFT_ARROW_Y) - SMALL_ARROW_SIDE / 2
# define SMALL_X_FLOOR_RIGHT_ARROW_EX (SMALL_X_FLOOR_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE)) + SMALL_ARROW_SIDE
# define SMALL_X_FLOOR_RIGHT_ARROW_EY (SMALL_X_FLOOR_LEFT_ARROW_Y) + SMALL_ARROW_SIDE / 2
# define SMALL_X_FLOOR_VALUE_X SMALL_X_FLOOR_LEFT_ARROW_X + SMALL_ARROW_GAP / 2 - 5
# define SMALL_X_FLOOR_VALUE_Y SMALL_X_FLOOR_LEFT_ARROW_Y - 10

# define SMALL_Y_FLOOR_LEFT_ARROW_X 1159
# define SMALL_Y_FLOOR_LEFT_ARROW_Y 842
# define SMALL_Y_FLOOR_LEFT_ARROW_SX SMALL_Y_FLOOR_LEFT_ARROW_X
# define SMALL_Y_FLOOR_LEFT_ARROW_SY SMALL_Y_FLOOR_LEFT_ARROW_Y - SMALL_ARROW_SIDE / 2
# define SMALL_Y_FLOOR_LEFT_ARROW_EX SMALL_Y_FLOOR_LEFT_ARROW_X + SMALL_ARROW_SIDE
# define SMALL_Y_FLOOR_LEFT_ARROW_EY SMALL_Y_FLOOR_LEFT_ARROW_Y + SMALL_ARROW_SIDE / 2
# define SMALL_Y_FLOOR_RIGHT_ARROW_SX (SMALL_Y_FLOOR_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE))
# define SMALL_Y_FLOOR_RIGHT_ARROW_SY (SMALL_Y_FLOOR_LEFT_ARROW_Y) - SMALL_ARROW_SIDE / 2
# define SMALL_Y_FLOOR_RIGHT_ARROW_EX (SMALL_Y_FLOOR_LEFT_ARROW_X + (SMALL_ARROW_GAP - SMALL_ARROW_SIDE)) + SMALL_ARROW_SIDE
# define SMALL_Y_FLOOR_RIGHT_ARROW_EY (SMALL_Y_FLOOR_LEFT_ARROW_Y) + SMALL_ARROW_SIDE / 2
# define SMALL_Y_FLOOR_VALUE_X SMALL_Y_FLOOR_LEFT_ARROW_X + SMALL_ARROW_GAP / 2 - 5
# define SMALL_Y_FLOOR_VALUE_Y SMALL_Y_FLOOR_LEFT_ARROW_Y - 10

#define WALL_TYPE_SIDE 30*/

#endif
